version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
  postgres_db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
volumes:
  postgres_data: