version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: python main.py

  postgres_db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
volumes:
  postgres_data: